language: php

php:
  - 5.6
  - 7.0

install:
  composer install

script:
  vendor/bin/phpunit

before_install:
  - cp .env.travis .env
  - mysql -e 'CREATE DATABASE foro_test;'
  - composer self-update;
  - composer install --no-interaction;
  - php artisan migrate;

services:
  - mysql

addons:
  mariadb: '10.0'