language: php

php:
  - 5.6
  - 7.0

install:
  composer install

script:
  vendor/bin/phpunit

before_install:
  - cp .env.travis .env
  - mysql -e 'CREATE DATABASE foro_tests;'
  - composer install --prefer-source --no-interaction
  - php artisan migrate --force

services:
  - mysql

addons:
  mariadb: '10.0'